### ISSUE TITLE
Cann't build for android

### ISSUE THREAD

**Issue by gkopylov** [AllJoyn-Cordova/cordova-plugin-alljoyn#53]
I have some problem when building it for Android.

Step to reproduce(on Ubuntu 14.04, nodejs v0.12.6, cordova 5.1.1, on this commit b0fb9798):

```
cordova create hello com.example.hello HelloWorld
cordova plugin add https://github.com/AllJoyn-Cordova/cordova-plugin-alljoyn.git
cordova platform add android
cordova build android
```

After these steps there are many errors like so:

```
/home/german/projects/hello/platforms/android/src/org/allseen/alljoyn/AllJoynCordova.java:54: error: cannot find symbol
    private AJ_BusAttachment bus;
            ^
  symbol:   class AJ_BusAttachment
  location: class AllJoynCordova
/home/german/projects/hello/platforms/android/src/org/allseen/alljoyn/AllJoynCordova.java:55: error: cannot find symbol
    private AJ_Object proxyObjects;
            ^
  symbol:   class AJ_Object
  location: class AllJoynCordova
/home/german/projects/hello/platforms/android/src/org/allseen/alljoyn/AllJoynCordova.java:56: error: cannot find symbol
    private AJ_Object appObjects;
            ^
  symbol:   class AJ_Object
  location: class AllJoynCordova
/home/german/projects/hello/platforms/android/src/org/allseen/alljoyn/AllJoynCordova.java:60: error: cannot find symbol
    private _AJ_Message m_pMsg = new _AJ_Message();
            ^
  symbol:   class _AJ_Message
  location: class AllJoynCordova
/home/german/projects/hello/platforms/android/src/org/allseen/alljoyn/AllJoynCordova.java:65: error: cannot find symbol
    _AJ_Message m_pCallbackMessagePtr = null;
    ^
  symbol:   class _AJ_Message
  location: class AllJoynCordova
/home/german/projects/hello/platforms/android/src/org/allseen/alljoyn/AllJoynCordova.java:1306: error: cannot find symbol
    JSONObject getMsgInfo(_AJ_Message pMsg) throws JSONException
                          ^
  symbol:   class _AJ_Message
  location: class AllJoynCordova
/home/german/projects/hello/platforms/android/src/org/allseen/alljoyn/AllJoynCordova.java:1333: error: cannot find symbol
    void sendSuccessArray(JSONArray argumentValues, CallbackContext callbackContext, boolean keepCallback, _AJ_Message pMsg) throws JSONException
                                                                                                           ^
  symbol:   class _AJ_Message
  location: class AllJoynCordova
/home/german/projects/hello/platforms/android/src/org/allseen/alljoyn/AllJoynCordova.java:1393: error: cannot find symbol
    void sendSuccessDictionary(JSONObject argumentValues, CallbackContext callbackContext, boolean keepCallback, _AJ_Message pMsg) throws JSONException
                                                                                                                 ^
  symbol:   class _AJ_Message
  location: class AllJoynCordova
/home/german/projects/hello/platforms/android/src/org/allseen/alljoyn/AllJoynCordova.java:1551: error: cannot find symbol
    AJ_Status UnmarshalArgs(_AJ_Message msg, StringBuffer sig, JSONArray args, StringBuffer nested) throws JSONException
                            ^
  symbol:   class _AJ_Message
  location: class AllJoynCordova
/home/german/projects/hello/platforms/android/src/org/allseen/alljoyn/AllJoynCordova.java:1551: error: cannot find symbol
    AJ_Status UnmarshalArgs(_AJ_Message msg, StringBuffer sig, JSONArray args, StringBuffer nested) throws JSONException
    ^
  symbol:   class AJ_Status
  location: class AllJoynCordova
/home/german/projects/hello/platforms/android/src/org/allseen/alljoyn/AllJoynCordova.java:1854: error: cannot find symbol
    JSONArray AJ_UnmarshalArgs(_AJ_Message msg, String signature)
                               ^
  symbol:   class _AJ_Message
  location: class AllJoynCordova
```

And after all of this:

```
:compileDebugJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 14.305 secs

/home/german/projects/hello/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /home/german/projects/hello/platforms/android/gradlew with args: cdvBuildDebug,-b,/home/german/projects/hello/platforms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /home/german/projects/hello/platforms/android/cordova/build: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: /home/german/projects/hello/platforms/android/cordova/build: Command failed with exit code 1
    at ChildProcess.whenDone (/home/german/.nvm/versions/node/v0.12.6/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```

But when I add this plugin like so `cordova plugin add org.allseen.alljoyn`, there is some errors too:

```
npm http GET http://cordova.iriscouch.com/registry/_design/app/_rewrite/org.allseen.alljoyn/-/org.allseen.alljoyn-0.0.4.tgz
npm http 200 http://cordova.iriscouch.com/registry/_design/app/_rewrite/org.allseen.alljoyn/-/org.allseen.alljoyn-0.0.4.tgz
Installing "org.allseen.alljoyn" for android
Cloning ajtcl from: https://github.com/AllJoyn-Cordova/ajtcl.git
Checking out branch: RB14.12
Cloning ajtcl-android from: https://github.com/irjudson/ajtcl-android.git
Failed to install 'org.allseen.alljoyn':Error: ENOENT, no such file or directory '/home/german/projects/hello/plugins/org.allseen.alljoyn/www/AllJoyn.js'
...
```

So I need to manually add this file(AllJoyn.js). And it works! :-) 

(Btw I have some problem when build with npm plugin too https://www.npmjs.com/package/alljoyn)

Ok, when I manually add this file this plugin appear to be only a thin client, but no a router. So I need to build an additional app with alljoyn sdk to have a router.

Can you fix these problems than I mentioned above? So the building app were not so painful :-) 
And please add a router to this plugin so there were ability to use all the features of alljoyn system.

**Comment by vjrantal** [comment]
Thanks for reporting the issue.

Could you confirm that you have installed the dependencies mentioned at https://github.com/AllJoyn-Cordova/cordova-plugin-alljoyn#building-for-android and you have ant, gradle and swig found from your PATH?

The CI built the plugin for Android on Ubuntu today (see https://circleci.com/gh/AllJoyn-Cordova/cordova-plugin-alljoyn/18). You can see from https://github.com/AllJoyn-Cordova/cordova-plugin-alljoyn/blob/master/circle.yml how we install the build pre-requisite on the CI machine.

> But when I add this plugin like so cordova plugin add org.allseen.alljoyn, there is some errors too

Right now, I recommend adding the plugin from GitHub master branch, because I am not 100% sure the published plugin in npm registry has the very latest.

**Comment by gkopylov** [comment]
Yeah, I installed all necessary dependencies Ant, Gradle, Swig and SDK with NDK for Android with  corresponding PATH in the environment.

**Comment by gkopylov** [comment]
Ok, I'll see how you install it a little later. Maybe my libs(Ant, Gradle, Swig) have wrong versions...(Btw I installed it from ubuntu original repository)

**Comment by vjrantal** [comment]
> Ok, I'll see how you install it a little later.

If you end up doing this, please report back how it went.

I noticed there was one dependency that isn't well documented in our instructions and that relates to Android built tools versions.

We use version 20.0.0 (https://github.com/AllJoyn-Cordova/cordova-plugin-alljoyn/blob/9cc62da61d32e830bc78fa2289d3e257c494694d/src/android/gradle/build.gradle#L29), but there is no automation or insurance that it is installed. Circle CI has that version by default so the installation is not visible in our CI setup.

I created a more verbose output from my build environment to https://gist.github.com/vjrantal/a7d738fffcb5e960e97a. The line at https://gist.github.com/vjrantal/a7d738fffcb5e960e97a#file-cmd-output-txt-L71 shows how I check the existence of build tools version 20.0.0. If that isn't available on your machine, please install that version using Android SDK manager or from command line with something like:

```
$ android update sdk --no-ui --all --filter build-tools-20.0.0
```

**Comment by gkopylov** [comment]
I checked all dependencies and install necessary versions. Sorry for long delay.

```
german@german:~/projects/BuildTestApp$ ant -version
Apache Ant(TM) version 1.9.3 compiled on April 8 2014


german@german:~/projects/BuildTestApp$ gradle -v

------------------------------------------------------------
Gradle 2.5
------------------------------------------------------------

Build time:   2015-07-08 07:38:37 UTC
Build number: none
Revision:     093765bccd3ee722ed5310583e5ed140688a8c2b

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.7.0_79 (Oracle Corporation 24.79-b02)
OS:           Linux 3.13.0-57-generic amd64


german@german:~/projects/BuildTestApp$ swig -version

SWIG Version 3.0.2

Compiled with g++ [x86_64-unknown-linux-gnu]

Configured options: +pcre

Please see http://www.swig.org for reporting bugs and further information


german@german:~/projects/BuildTestApp$ echo $ANDROID_HOME
/home/german/android/android-sdk-linux


german@german:~/projects/BuildTestApp$ echo $ANDROID_NDK_HOME
/home/german/android/android/android-ndk-r10e


german@german:~/projects/BuildTestApp$ ndk-build -version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for x86_64-pc-linux-gnu


german@german:~/projects/BuildTestApp$ android list targets
Available Android targets:
----------
id: 1 or "android-19"
     Name: Android 4.4.2
     Type: Platform
     API level: 19
     Revision: 4
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
 Tag/ABIs : default/armeabi-v7a, default/x86
----------
id: 2 or "android-21"
     Name: Android 5.0.1
     Type: Platform
     API level: 21
     Revision: 2
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in, AndroidWearRound, AndroidWearSquare, AndroidWearRound, AndroidWearSquare
 Tag/ABIs : android-tv/armeabi-v7a, android-tv/x86, android-wear/armeabi-v7a, android-wear/x86, default/armeabi-v7a, default/x86, default/x86_64
----------
id: 3 or "android-22"
     Name: Android 5.1.1
     Type: Platform
     API level: 22
     Revision: 2
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in, AndroidWearRound, AndroidWearRound400x400, AndroidWearRoundChin320x290, AndroidWearSquare, AndroidWearSquare320x320, AndroidWearRound, AndroidWearRound400x400, AndroidWearRoundChin320x290, AndroidWearSquare, AndroidWearSquare320x320
 Tag/ABIs : android-tv/armeabi-v7a, android-tv/x86, android-wear/armeabi-v7a, android-wear/x86, default/armeabi-v7a, default/x86, default/x86_64
----------
id: 4 or "Google Inc.:Google APIs:21"
     Name: Google APIs
     Type: Add-On
     Vendor: Google Inc.
     Revision: 1
     Description: Android + Google APIs
     Based on Android 5.0.1 (API level 21)
     Libraries:
      * com.google.android.media.effects (effects.jar)
          Collection of video effects
      * com.android.future.usb.accessory (usb.jar)
          API for USB Accessories
      * com.google.android.maps (maps.jar)
          API for Google Maps
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in, AndroidWearRound, AndroidWearSquare, AndroidWearRound, AndroidWearSquare
 Tag/ABIs : google_apis/armeabi-v7a, google_apis/x86, google_apis/x86_64
----------
id: 5 or "Google Inc.:Google APIs:22"
     Name: Google APIs
     Type: Add-On
     Vendor: Google Inc.
     Revision: 1
     Description: Android + Google APIs
     Based on Android 5.1.1 (API level 22)
     Libraries:
      * com.google.android.media.effects (effects.jar)
          Collection of video effects
      * com.android.future.usb.accessory (usb.jar)
          API for USB Accessories
      * com.google.android.maps (maps.jar)
          API for Google Maps
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in, AndroidWearRound, AndroidWearRound400x400, AndroidWearRoundChin320x290, AndroidWearSquare, AndroidWearSquare320x320, AndroidWearRound, AndroidWearRound400x400, AndroidWearRoundChin320x290, AndroidWearSquare, AndroidWearSquare320x320
 Tag/ABIs : google_apis/armeabi-v7a, google_apis/x86, google_apis/x86_64


german@german:~/projects/BuildTestApp$ ls -la ~/android/android-sdk-linux/build-tools/20.0.0/
total 49352
drwxrwxr-x 4 german german     4096 Jul 16 18:46 .
drwxrwxr-x 7 german german     4096 Jul 16 19:07 ..
-rwxrwxr-x 1 german german  1123893 Jul 16 18:46 aapt
-rwxrwxr-x 1 german german   278379 Jul 16 18:46 aidl
-rwxrwxr-x 1 german german  3570836 Jul 16 18:46 arm-linux-androideabi-ld
-rwxrwxr-x 1 german german    37074 Jul 16 18:46 bcc_compat
-rwxrwxr-x 1 german german   473695 Jul 16 18:46 dexdump
-rwxrwxr-x 1 german german     2577 Jul 16 18:46 dx
-rwxrwxr-x 1 german german  3570836 Jul 16 18:46 i686-linux-android-ld
drwxrwxr-x 2 german german     4096 Jul 16 18:46 lib
-rwxrwxr-x 1 german german   332539 Jul 16 18:46 libbcc.so
-rwxrwxr-x 1 german german   927028 Jul 16 18:46 libbcinfo.so
-rwxrwxr-x 1 german german 15372369 Jul 16 18:46 libclang.so
-rwxrwxr-x 1 german german 21101517 Jul 16 18:46 libLLVM.so
-rwxrwxr-x 1 german german  1672353 Jul 16 18:46 llvm-rs-cc
-rwxrwxr-x 1 german german  1919720 Jul 16 18:46 mipsel-linux-android-ld
-rw-rw-r-- 1 german german    10800 Jul 16 18:46 NOTICE.txt
drwxrwxr-x 5 german german     4096 Jul 16 18:46 renderscript
-rw-rw-r-- 1 german german    16504 Jul 16 18:46 source.properties
-rwxrwxr-x 1 german german    65609 Jul 16 18:46 zipalign


german@german:~/projects/BuildTestApp$ cordova -version
5.1.1
```

But when I build it I get this error:

```
FAILURE: 
Build failed with an exception.




* What went wrong:

Execution failed for task ':AllJoynLib:compileArmReleaseNdk'.

> 
NDK not configured.

  Download the NDK from http://developer.android.com/tools/sdk/ndk/.Then add ndk.dir=path/to/ndk in local.properties.

  (On Windows, make sure you escape backslashes, e.g. C:\\ndk rather than C:\ndk)
```

When I use https://build.phonegap.com and include `<gap:plugin name="cordova-plugin-alljoyn" source="npm" />` there are such errors:

```
Error - Plugin error (you probably need to remove plugin files from your app): npm http GET https://registry.npmjs.org/cordova-plugin-alljoyn npm http 200 https://registry.npmjs.org/cordova-plugin-alljoyn npm http GET https://registry.npmjs.org/cordova-plugin-alljoyn/-/cordova-plugin-alljoyn-0.0.5.tgz npm http 200 https://registry.npmjs.org/cordova-plugin-alljoyn/-/cordova-plugin-alljoyn-0.0.5.tgz Error during processing of action! Attempting to revert... Failed to install 'cordova-plugin-alljoyn':Error: Uh oh! "/tmp/gimlet/1648/21bd663a-1d4b-11e4-817b-5a39905c16a2/www_android/project/cordova/plugins/cordova-plugin-alljoyn/src/ajtcl/src/aj_about.c" not found! at Object.module.exports.common.copyFile (/home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/cordova-lib/src/plugman/platforms/common.js:38:40) at Object.module.exports.common.copyNewFile (/home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/cordova-lib/src/plugman/platforms/common.js:69:16) at Object.module.exports.source-file.install (/home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/cordova-lib/src/plugman/platforms/android.js:78:20) at installWrapper (/home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/cordova-lib/src/platforms/platforms.js:76:32) at Object.ActionStack.process
```

and so on.

The only one way to build app with your plugin I found is to add plugin like so `cordova plugin add org.allseen.alljoyn` and manually add file this AllJoyn.js.

And what about including AllJoyn Router to this plugin?

**Comment by gkopylov** [comment]
Ok, I finally get it works. All you need is:

```
cd <your project path>/platforms/android/
android update project -p .
```

and then in the file `local.properties` you should add line:

```
ndk.dir=/path/to/your/ndk
```

Maybe it is worth to add this in the README file? I can send pull request for this.

**Comment by vjrantal** [comment]
> and then in the file `local.properties` you should add line

In my environment and in the CI, the NDK is found via setting `$ANDROID_NDK_HOME` to the correct location. However, based on your comment earlier in this issue, you might have that environment variable properly set. Would be great if you could double-check if you had that set in the session where you tried the build and also, seems like the CI also has `$ANDROID_NDK` set (https://github.com/AllJoyn-Cordova/cordova-plugin-alljoyn/blob/f8ec9b786ea9113d20c1354ce4d3591d8061a5d6/circle.yml#L3) so perhaps to try if setting that makes a difference (on my Mac, it isn't needed).

If defining the NDK location per-project in the `local.properties` is required in some environments, I think it would be good to mention that in the instructions so a pull request is welcome.

**Comment by vjrantal** [comment]
> And what about including AllJoyn Router to this plugin?

It has been discussed and the value of having a bundled router is understood, but at least the team that did the initial implementation of this plugin does not have active development or concrete plans to include a router. The thinking is that the main use case for the plugin is such where the router exists outside of the Cordova app.

Everything is possible, but including a router isn't trivial, because this plugin is based on the ajtcl, which doesn't include a router implementation.

If having a router within the app is mandatory in your use case, this plugin might not be the perfect fit.

**Comment by gkopylov** [comment]
Yeah, you are right, setting appropriate ANDROID_NDK has solved the problem. Thank you for your help!
